services:
  mysql:
    image: mysql:8.4
    container_name: multidb-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: multidb_demo
      MYSQL_USER: multidb_demo
      MYSQL_PASSWORD: multidb_demo_123
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./sql/mysql:/docker-entrypoint-initdb.d

  postgres:
    image: postgres:16
    container_name: multidb-postgres
    environment:
      POSTGRES_DB: multidb_demo
      POSTGRES_USER: multidb_demo
      POSTGRES_PASSWORD: multidb_demo_123
    ports:
      - "5432:5432"
    volumes:
      - ./sql/postgres:/docker-entrypoint-initdb.d

